# Build settings
gems:
  - jemoji
  - jekyll-paginate
  - jekyll-redirect-from

# Site settings
title: "iland"
description: > # this means to ignore newlines until "email:"
    cyclad-punk comic in alternative 1830s
# No man is an iland - entire of itself

email: ilandcomics@gmail.com
#blog logo
logo: "/assets/images/logo_map.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/chapter_clouds_page02_f5.jpg"

name: 'Nikos Tsouknidas & Rob Morgan'
author: 'Nikos Tsouknidas'
author_image: "/assets/images/author.jpg"

paginate:	5
paginate_path: '/blog/page:num/'

url: "http://www.ilandcomic.co.uk" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@tsoukn'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

google_analytics: UA-101866150-1

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/AboutThisLater
    desc: Rob Morgan on twitter
    share_url: http://twitter.com/share
    share_title: ?text=iland%20comic%20-%20
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/n.tsouk
    desc: Connect with me facebook
    share_url: https://www.facebook.com/dialog/feed
    share_title: ?app_id=836888063133831&display=popup&
    share_link: "&link="

  # - icon:	github
  #   url:	https://github.com/tsouk
  #   desc:	Fork me on github
  #   share_url:
  #   share_title:
  #   share_link:

  - icon: instagram
    url:  https://instagram.com/tsouk.n
    desc: Nikos Tsouknidas on instagram
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
